class gameMsg():
    
    def submit_player_choise(self,player_id,choise):
        '''player_id (string, generated by uuid4), choise (string) '石头'/'剪刀'/'布'
        '''
        return {'event_type': 'to_game',
                'event_act': 'set_player_choise',
                'event_obj': [player_id, choise]
                }

    def enquiry_result(self):
        return {'event_type': 'to_game',
                'event_act': 'enquiry_winner',
                'event_obj': None
                }

    def waiting_for_other_player(self):
        return {'event_type': 'to_all_player',
                'event_act': 'waiting_for_other_player',
                'event_obj': None
                }